### ISSUE TITLE
Add in tshirt sizing for management node

### ISSUE THREAD

**Issue by todkap** [ibm-cloud-architecture/refarch-privatecloud#13]
Article is not reflecting the latest changes where management node was introduced.

> refarch-privatecloud/Sizing.md

**Comment by patrocinio** [comment]
@VictorHavard Can you please add the recommended size for the management node? Thanks

**Comment by gyliu513** [comment]
This is ICP KC for the system requirement https://www.ibm.com/support/knowledgecenter/SSBS6K_2.1.0/supported_system_config/hardware_reqs.html

**Comment by todkap** [comment]
I think we can provide min, small, medium, and large guidance for good starting point (users still need to adjust for their env and this is good to track).

**Comment by VictorHavard** [comment]
Quite a lot has changed and the recommendations have also changed.  I am in the middle of a fresh install to capture all of the needed changes and will update the site when I have it complete.

**Comment by VictorHavard** [comment]
Stale
