### ISSUE TITLE
Is documentation ICP 3.1 ready?

### ISSUE THREAD

**Issue by gxvigo** [ibm-cloud-architecture/refarch-privatecloud#21]
Hi There, 
I am looking at the DR section of this repo and it mentions v2 of ICP.
I know v3 introduced a few changes, is the documentation sill valid?
As an example: https://github.com/ibm-cloud-architecture/refarch-privatecloud/blob/master/Resiliency/vmware-icp-dr.md
and all the links

Cheers, Giovanni

**Comment by gangchen03** [comment]
@gxvigo we are working on 3.1 updating. Some content like Terraform installation scripts and documents are up-to-date, some are still in progress, including the DR one.

**Comment by VictorHavard** [comment]
ICP is now obsolete, closing issue.
