### ISSUE TITLE
OpenShift HA document 'Adding users via htpasswd' needs to be earlier

### ISSUE THREAD

**Issue by macadech** [ibm-cloud-architecture/refarch-privatecloud#28]
Following the documentation, has you deploy OpenShift via ansible prior to setting up the htpasswd users on the 'Master' nodes.
Ideally the section called 'Adding users via htpasswd' should appear before the OpenShift install playbook.

**Comment by VictorHavard** [comment]
Is there a reason why it is better to do it before the install?

**Comment by macadech** [comment]
When I kicked off the install, it complained that the file /etc/origin/master/users.htpasswd did not exist on the master nodes

**Comment by VictorHavard** [comment]
If you are using LDAP integration then you will not have that file at all.  You can only have one authentication mechanism active at a time.  I have used both methods (htpasswd and LDAP) and they both work and I installed them in this order.  I would expect the complaint you got was more of a warning than an error.
