### ISSUE TITLE
Update the links to download OCP CLI

### ISSUE THREAD

**Issue by rsundara** [ibm-cloud-architecture/refarch-privatecloud#32]
Latest links are: 
wget -c https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.2.13.tar.gz
wget -c https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.2.13.tar.gz

**Comment by VictorHavard** [comment]
Links are updated very frequently (weekly or less sometimes), so changed link to parent directory so users always get the latest version
