### ISSUE TITLE
I'd suggest that you use inline code markdown (three backticks, newline, "text", three backticks) instead of the screencaps of console windows.

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-privatecloud#6]

**Comment by VictorHavard** [comment]
I have gone back and reformatted everything to makes sure linebreaks are correct and all code is marked as code.  They do not use the three backticks method above, but they all look correct as far as I can tell.  Is there a reason to use the specific format noted above other than just for formatting purposes?

**Comment by patrocinio** [comment]
@VictorHavard Only for formatting purposes. Thank you!

**Comment by VictorHavard** [comment]
Okay, then that has been corrected.  Everything should now be formatted correctly.
