### ISSUE TITLE
Are you familiar with devWorks recipes? Most of the howtos look like they would fit into that model better, which would expose them to better indexing on google

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-privatecloud#7]

**Comment by VictorHavard** [comment]
I found a lot of recipes out there, but nothing on the format of the recipe.  Can you provide more information about what specifically you mean as well as links to any documentation?

**Comment by patrocinio** [comment]
@VictorHavard Here is an example: https://developer.ibm.com/recipes/tutorials/automatic-generation-of-lets-encrypt-certificates-with-minikube/

**Comment by todkap** [comment]
I would like this to also be part of our ibm-cloud Medium publication.
https://medium.com/ibm-cloud
Likely we would want to talk more about creating HA for K8 (and how we did it for ICP).

**Comment by patrocinio** [comment]
Hello @todkap Can you point to what has been done regarding HA for ICP? Thanks

**Comment by todkap** [comment]
The current reference that is external are...
HA set up https://github.com/ibm-cloud-architecture/refarch-privatecloud/blob/master/Resiliency/Configure_HA_ICP_cluster.md) as well as a very basic sizing one (https://github.com/ibm-cloud-architecture/refarch-privatecloud/blob/master/Sizing.md) .

**Comment by VictorHavard** [comment]
stale
